python3 rnn_maths.py --epochs=50 --seqlen=2
python3 rnn_maths.py --epochs=50 --seqlen=3
python3 rnn_maths.py --epochs=50 --seqlen=4
python3 rnn_maths.py --epochs=50 --seqlen=5
python3 rnn_maths.py --epochs=50 --seqlen=6
python3 rnn_maths.py --epochs=50 --seqlen=7
python3 rnn_maths.py --epochs=50 --seqlen=8
python3 rnn_maths.py --epochs=50 --seqlen=9
python3 rnn_maths.py --epochs=50 --seqlen=10

python3 mingpt_maths.py --epochs=50 --seqlen=2
python3 mingpt_maths.py --epochs=50 --seqlen=3
python3 mingpt_maths.py --epochs=50 --seqlen=4
python3 mingpt_maths.py --epochs=50 --seqlen=5
python3 mingpt_maths.py --epochs=50 --seqlen=6
python3 mingpt_maths.py --epochs=50 --seqlen=7
python3 mingpt_maths.py --epochs=50 --seqlen=8
python3 mingpt_maths.py --epochs=50 --seqlen=9
python3 mingpt_maths.py --epochs=50 --seqlen=10
